#include "board.h"
#include "app.h"

void App(void);

spibus_t BOARD_SPIDEV_HANDLER;

int main()
{
    CLOCK_Init(100);
	CLOCK_InitUSBCLK();

    BOARD_Init();

    //SERIAL_Config(&BOARD_SERIAL0_HANDLER, SERIAL0);
    SERIAL_Config(&BOARD_SERIAL1_HANDLER, SERIAL1 | SERIAL_DATA_8B | SERIAL_PARITY_NONE | SERIAL_STOP_1B | SERIAL_SPEED_115200);
    SERIAL_Config(&BOARD_SERIAL3_HANDLER, SERIAL3 | SERIAL_DATA_8B | SERIAL_PARITY_NONE | SERIAL_STOP_1B | SERIAL_SPEED_115200);
    SERIAL_Config(&BOARD_SERIAL4_HANDLER, SERIAL4);

    DISPLAY_Init(1);
	LCD_Rotation(LCD_LANDSCAPE);
	LCD_Bkl(1);

    DBG_PIN_INIT;

    App();

	return 0;
}
